name: got_u_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.7.0
  dio: ^4.0.6
  lottie: 2.3.2
  get_storage: ^2.0.3
  font_awesome_flutter: ^10.4.0
  double_back_to_close_app: ^2.1.0
  url_launcher: ^6.1.11

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: '^0.13.1'
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: 'launcher_icon'
  image_path: 'assets/icons/icon.png'

flutter:
  assets:
    - assets/images/
    - assets/lotties/
  uses-material-design: true
